-- bi_dashboard.vm_unificado_sistemas_bi source

CREATE MATERIALIZED VIEW bi_dashboard.vm_unificado_sistemas_bi
TABLESPACE pg_default
AS SELECT y."CÓDIGO PROYECTO",
    y."NOMBRE PROYECTO",
    y."RESUMEN PROYECTO",
    y."DIRECCIÓN PROYECTO",
    y."FECHA REGISTRO",
    y."CÓDIGO ACTIVIDAD",
    y."ACTIVIDAD ECONÓMICA",
    y."CED/RUC PROPONENTE",
    y."NOMBRE PROPONENTE",
    w."direcciÓn" AS "DIRECCIÓN PROPONENTE",
    w."telÉfono" AS "TELEFONO PROPONENTE",
    w."TELÉFONO CELULAR" AS "CELULAR PROPONENTE",
    w."CORREO ELECTRÓNICO" AS "EMAIL PROPONENTE",
    w."TÍPO ORGANIZACIÓN",
    y."ÁREA RESPONSABLE PROYECTO",
    y."TIPO SECTOR",
    y."TIPO PERMISO AMBIENTAL",
    y."TIPO ENTE",
    y."PROVINCIA",
    y."CANTON",
    y."PARROQUIA",
    y."PROCESO",
    y."ESTADO PROCESO",
    y."FECHA INICIO PROCESO",
    y."FECHA FIN PROCESO",
    y."TAREA",
    y."ESTADO TAREA",
    y."FECHA INICIO TAREA",
    y."FECHA FIN TAREA",
    y."USUARIO TAREA",
    y."ESTADO PROYECTO",
    y."INTERSECTA CON",
    y."AREAS PROTEGIDAS",
    y."SISTEMA",
    y."NOMBRE ZONA",
    y."FINALIZADO CON RESOLUCION",
    y."NUMERO RESOLUCION",
    y."FECHA RESOLUCION",
    y."ENTE ACREDITADO",
    y."ESTADO TRÁMITE",
    y."ID AREA",
    y."SUPERFICIE PROYECTO",
    y."ESTRATÉGICO",
    z."CEDULA/RUC" AS "CEDULA/RUC USUARIO TAREA",
    z.nombres AS "NOMBRE USUARIO TAREA",
    z."direcciÓn" AS "DIRECCIÓN USUARIO TAREA",
    z."telÉfono" AS "TELEFENO USUARIO TAREA",
    z."TELÉFONO CELULAR" AS "CELULAR USUARIO TAREA",
    z."CORREO ELECTRÓNICO" AS "EMAIL USUARIO TAREA",
    z.rol AS "ROLUSUARIO TAREA",
    dias_laborable(y."FECHA INICIO PROCESO"::date, COALESCE(y."FECHA FIN PROCESO"::date::timestamp with time zone, now())::date) AS "DIAS TRANSCURRIDOS",
    ( SELECT DISTINCT t2."FECHA_CARGA"
           FROM dblink('dbname= suia_enlisy port=5632 host=172.16.0.179 user=postgres password=postgres'::text, '
					select DISTINCT pp."FECHA_CARGA" 
					  from coa_mae.tmp_rcoa_bi pp  
				   '::text) t2("FECHA_CARGA" timestamp without time zone)) AS "FECHA_CARGA_DATOS"
   FROM ( SELECT DISTINCT t1."CÓDIGO PROYECTO",
            t1."NOMBRE PROYECTO",
            t1."RESUMEN PROYECTO",
            t1."DIRECCIÓN PROYECTO",
            t1."FECHA REGISTRO",
            t1."CÓDIGO ACTIVIDAD",
            t1."ACTIVIDAD ECONÓMICA",
            t1."CED/RUC PROPONENTE",
            t1."NOMBRE PROPONENTE",
            t1."ÁREA RESPONSABLE PROYECTO",
            t1."TIPO SECTOR",
            t1."TIPO PERMISO AMBIENTAL",
            t1."TIPO ENTE",
            t1."PROVINCIA",
            t1."CANTON",
            t1."PARROQUIA",
            t1."PROCESO",
            t1."ESTADO PROCESO",
            t1."FECHA INICIO PROCESO",
            t1."FECHA FIN PROCESO",
            t1."TAREA",
            t1."ESTADO TAREA",
            t1."FECHA INICIO TAREA",
            t1."FECHA FIN TAREA",
            t1."USUARIO TAREA",
            t1."ESTADO PROYECTO",
            t1."INTERSECTA CON",
            t1."AREAS PROTEGIDAS",
            t1."SISTEMA",
            t1."NOMBRE ZONA",
            t1."FINALIZADO CON RESOLUCION",
            t1."NUMERO RESOLUCION",
            t1."FECHA RESOLUCION",
            ''::text AS "ENTE ACREDITADO",
            t1."ESTADO TRÁMITE",
            t1."ID AREA",
            t1."SUPERFICIE PROYECTO",
            ''::text AS "ESTRATÉGICO"
           FROM dblink('dbname= suia_enlisy port=5632 host=172.16.0.179 user=postgres password=postgres'::text, '
						select pp."CÓDIGO PROYECTO",
							    pp."NOMBRE PROYECTO",
							    pp."RESUMEN PROYECTO",
                                pp."DIRECCIÓN PROYECTO",
							    pp."FECHA REGISTRO",
							    pp."CÓDIGO ACTIVIDAD", 
							    pp."ACTIVIDAD ECONÓMICA",
							    pp."CED/RUC PROPONENTE",
							    pp."NOMBRE PROPONENTE",
							    pp."ÁREA RESPONSABLE PROYECTO",
							    pp."TIPO SECTOR",
							    pp."TIPO PERMISO AMBIENTAL",
							    pp."TIPO ENTE",
							    pp."PROVINCIA",
							    pp."CANTON",
							    pp."PARROQUIA",
							    pp."PROCESO",
							    pp."ESTADO PROCESO",
							    pp."FECHA INICIO PROCESO",
							    pp."FECHA FIN PROCESO",
							    pp."TAREA",
							    pp."ESTADO TAREA",
							    pp."FECHA INICIO TAREA",
							    pp."FECHA FIN TAREA",
							    pp."USUARIO TAREA",
							    pp."ESTADO PROYECTO",
							    pp."INTERSECTA CON",
							    pp."AREAS PROTEGIDAS",
							    pp."SISTEMA",
							    pp."NOMBRE ZONA",
							    pp."FINALIZADO CON RESOLUCION",
							    pp."NUMERO RESOLUCION",
                                pp."FECHA RESOLUCION",
							    '''' "ENTE ACREDITADO",
							    pp."ESTADO TRÁMITE",
							    pp."ID AREA",
							    pp."SUPERFICIE PROYECTO",
							    '''' "ESTRATÉGICO"								
						from suia_iii.tmp_coa_bi pp
'::text) t1("CÓDIGO PROYECTO" character varying(255), "NOMBRE PROYECTO" text, "RESUMEN PROYECTO" text, "DIRECCIÓN PROYECTO" text, "FECHA REGISTRO" timestamp without time zone, "CÓDIGO ACTIVIDAD" text, "ACTIVIDAD ECONÓMICA" text, "CED/RUC PROPONENTE" text, "NOMBRE PROPONENTE" text, "ÁREA RESPONSABLE PROYECTO" text, "TIPO SECTOR" text, "TIPO PERMISO AMBIENTAL" text, "TIPO ENTE" text, "PROVINCIA" text, "CANTON" text, "PARROQUIA" text, "PROCESO" text, "ESTADO PROCESO" text, "FECHA INICIO PROCESO" timestamp without time zone, "FECHA FIN PROCESO" timestamp without time zone, "TAREA" text, "ESTADO TAREA" text, "FECHA INICIO TAREA" timestamp without time zone, "FECHA FIN TAREA" timestamp without time zone, "USUARIO TAREA" text, "ESTADO PROYECTO" text, "INTERSECTA CON" text, "AREAS PROTEGIDAS" text, "SISTEMA" text, "NOMBRE ZONA" character varying(500), "FINALIZADO CON RESOLUCION" character varying(500), "NUMERO RESOLUCION" character varying(500), "FECHA RESOLUCION" timestamp without time zone, "ENTE ACREDITADO" character varying(500), "ESTADO TRÁMITE" character varying(500), "ID AREA" integer, "SUPERFICIE PROYECTO" double precision, "ESTRATÉGICO" character varying(500))
        UNION ALL
         SELECT DISTINCT t2."CÓDIGO PROYECTO",
            t2."NOMBRE PROYECTO",
            t2."RESUMEN PROYECTO",
            t2."DIRECCIÓN PROYECTO",
            t2."FECHA REGISTRO",
            t2."CÓDIGO ACTIVIDAD",
            t2."ACTIVIDAD ECONÓMICA",
            t2."CED/RUC PROPONENTE",
            t2."NOMBRE PROPONENTE",
            t2."ÁREA RESPONSABLE PROYECTO",
            t2."TIPO SECTOR",
            t2."TIPO PERMISO AMBIENTAL",
            t2."TIPO ENTE",
            t2."PROVINCIA",
            t2."CANTON",
            t2."PARROQUIA",
            t2."PROCESO",
            t2."ESTADO PROCESO",
            t2."FECHA INICIO PROCESO",
            t2."FECHA FIN PROCESO",
            t2."TAREA",
            t2."ESTADO TAREA",
            t2."FECHA INICIO TAREA",
            t2."FECHA FIN TAREA",
            t2."USUARIO TAREA",
            t2."ESTADO PROYECTO",
            t2."INTERSECTA CON",
            t2."AREAS PROTEGIDAS",
            t2."SISTEMA",
            t2."NOMBRE ZONA",
            t2."FINALIZADO CON RESOLUCION",
            t2."NUMERO RESOLUCION",
            t2."FECHA RESOLUCION",
            ''::text AS "ENTE ACREDITADO",
                CASE
                    WHEN t2."ESTADO PROYECTO" = 'Completado No Favorable'::text THEN 'FINALIZADO NO FAVORABLE'::text
                    WHEN t2."ESTADO PROYECTO" = 'Completado'::text THEN 'FINALIZADO EXITO'::text
                    WHEN t2."ESTADO PROYECTO" = 'En trámite'::text AND t2."TIPO PERMISO AMBIENTAL" ~~ '%Licen%'::text AND t2."FECHA REGISTRO" >= '2021-10-12 00:00:00'::timestamp without time zone AND t2.estudio > 0 THEN 'PROCESO FISICO'::text
                    WHEN t2."ESTADO PROYECTO" = 'En trámite'::text AND t2."TIPO PERMISO AMBIENTAL" ~~ '%Licen%'::text AND t2."FECHA REGISTRO" >= '2021-10-12 00:00:00'::timestamp without time zone AND t2.estudio IS NULL THEN 'EN TRÁMITE HASTA LLEGAR A PROCESO FÍSICO'::text
                    WHEN t2."ESTADO PROYECTO" = 'En trámite'::text AND t2."TIPO PERMISO AMBIENTAL" ~~ '%Regist%'::text AND t2."FECHA REGISTRO" >= '2023-06-02 00:00:00'::timestamp without time zone AND (t2."TIPO SECTOR" = ANY (ARRAY['Minería'::text, 'Hidrocarburos'::text])) AND t2.registro > 0 THEN 'PROCESO FISICO'::text
                    WHEN t2."ESTADO PROYECTO" = 'En trámite'::text AND t2."TIPO PERMISO AMBIENTAL" ~~ '%Regist%'::text AND t2."FECHA REGISTRO" >= '2023-06-02 00:00:00'::timestamp without time zone AND (t2."TIPO SECTOR" = ANY (ARRAY['Minería'::text, 'Hidrocarburos'::text])) AND t2.registro IS NULL THEN 'EN TRÁMITE HASTA LLEGAR A PROCESO FÍSICO'::text
                    ELSE 'EN TRÁMITE'::text
                END AS "ESTADO TRÁMITE",
            t2."ID AREA",
            t2."SUPERFICIE PROYECTO",
            t2."ESTRATÉGICO"
           FROM dblink('dbname= suia_enlisy port=5632 host=172.16.0.179 user=postgres password=postgres'::text, '
select pp."CÓDIGO PROYECTO",
    pp."NOMBRE PROYECTO",
    pp."RESUMEN PROYECTO",
    pp."DIRECCIÓN PROYECTO",
    pp."FECHA REGISTRO",
    pp."CÓDIGO ACTIVIDAD", 
    pp."ACTIVIDAD ECONÓMICA",
    pp."CED/RUC PROPONENTE",
    pp."NOMBRE PROPONENTE",
    pp."ÁREA RESPONSABLE PROYECTO",
    pp."TIPO SECTOR",
    pp."TIPO PERMISO AMBIENTAL",
    pp."TIPO ENTE",
    pp."PROVINCIA",
    pp."CANTON",
    pp."PARROQUIA",
    pp."PROCESO",
    pp."ESTADO PROCESO",
    pp."FECHA INICIO PROCESO",
    pp."FECHA FIN PROCESO",
    pp."TAREA",
    pp."ESTADO TAREA",
    pp."FECHA INICIO TAREA",
    pp."FECHA FIN TAREA",
    pp."USUARIO TAREA",
    pp."ESTADO PROYECTO",
    pp."INTERSECTA CON",
    pp."AREAS PROTEGIDAS",
    pp."SISTEMA",
    pp."NOMBRE ZONA",
    pp."FINALIZADO CON RESOLUCION",
    pp."NUMERO RESOLUCION",   
    pp."FECHA RESOLUCION",
    pp."ESTADO TRÁMITE",
    '''' "ENTE ACREDITADO",
    t2.estudio,
    t3.registro,
    pp."ID AREA",
    pp."SUPERFICIE PROYECTO",
    '''' "ESTRATÉGICO"    
from coa_mae.tmp_rcoa_bi pp  
left join (select "CÓDIGO PROYECTO" as codigo, COUNT(DISTINCT "CÓDIGO PROYECTO") as estudio FROM coa_mae.tmp_rcoa_bi
            where "TIPO PERMISO AMBIENTAL" like ''%Licen%'' and "PROCESO" in( ''Estudio Impacto Ambiental'',  ''Estudio Impacto Ambiental v2'')
            and "ESTADO PROCESO" = ''Completado'' GROUP BY "CÓDIGO PROYECTO") as t2 on pp."CÓDIGO PROYECTO" = t2.codigo
left join (select "CÓDIGO PROYECTO" as codigo, COUNT(DISTINCT "CÓDIGO PROYECTO") as registro FROM coa_mae.tmp_rcoa_bi
            where "TIPO PERMISO AMBIENTAL" like ''%Registr%'' and "PROCESO" = ''Registro Ambiental'' GROUP BY "CÓDIGO PROYECTO") as t3 on pp."CÓDIGO PROYECTO" = t3.codigo
'::text) t2("CÓDIGO PROYECTO" character varying(255), "NOMBRE PROYECTO" text, "RESUMEN PROYECTO" text, "DIRECCIÓN PROYECTO" text, "FECHA REGISTRO" timestamp without time zone, "CÓDIGO ACTIVIDAD" text, "ACTIVIDAD ECONÓMICA" text, "CED/RUC PROPONENTE" text, "NOMBRE PROPONENTE" text, "ÁREA RESPONSABLE PROYECTO" text, "TIPO SECTOR" text, "TIPO PERMISO AMBIENTAL" text, "TIPO ENTE" text, "PROVINCIA" text, "CANTON" text, "PARROQUIA" text, "PROCESO" text, "ESTADO PROCESO" text, "FECHA INICIO PROCESO" timestamp without time zone, "FECHA FIN PROCESO" timestamp without time zone, "TAREA" text, "ESTADO TAREA" text, "FECHA INICIO TAREA" timestamp without time zone, "FECHA FIN TAREA" timestamp without time zone, "USUARIO TAREA" text, "ESTADO PROYECTO" text, "INTERSECTA CON" text, "AREAS PROTEGIDAS" text, "SISTEMA" text, "NOMBRE ZONA" character varying(500), "FINALIZADO CON RESOLUCION" character varying(500), "NUMERO RESOLUCION" character varying(500), "FECHA RESOLUCION" timestamp without time zone, "ENTE ACREDITADO" character varying(500), "ESTADO TRÁMITE" character varying(500), estudio integer, registro integer, "ID AREA" integer, "SUPERFICIE PROYECTO" double precision, "ESTRATÉGICO" character varying(500))
        UNION ALL
         SELECT DISTINCT t3."CÓDIGO PROYECTO",
            t3."NOMBRE PROYECTO",
            t3."RESUMEN PROYECTO",
            t3."DIRECCIÓN PROYECTO",
            t3."FECHA REGISTRO",
            t3."CÓDIGO ACTIVIDAD",
            t3."ACTIVIDAD ECONÓMICA",
            t3."CED/RUC PROPONENTE",
            t3."NOMBRE PROPONENTE",
            t3."ÁREA RESPONSABLE PROYECTO",
            t3."TIPO SECTOR",
            t3."TIPO PERMISO AMBIENTAL",
            t3."TIPO ENTE",
            t3."PROVINCIA",
            t3."CANTON",
            t3."PARROQUIA",
            t3."PROCESO",
            t3."ESTADO PROCESO",
            t3."FECHA INICIO PROCESO",
            t3."FECHA FIN PROCESO",
            t3."TAREA",
            t3."ESTADO TAREA",
            t3."FECHA INICIO TAREA",
            t3."FECHA FIN TAREA",
            t3."USUARIO TAREA",
            t3."ESTADO PROYECTO",
            t3."INTERSECTA CON",
            t3."AREAS PROTEGIDAS",
            t3."SISTEMA",
            t3."NOMBRE ZONA",
            t3."FINALIZADO CON RESOLUCION",
            t3."NUMERO RESOLUCION",
            t3."FECHA RESOLUCION",
            t3."ENTE ACREDITADO",
            t3."ESTADO TRÁMITE",
            t3."ID AREA",
            t3."SUPERFICIE PROYECTO",
            t3."ESTRATÉGICO"
           FROM dblink('dbname= jbpmdb_prod_old port=5432 host=172.16.0.226 user=postgres password=postgres'::text, '
select pp."CÓDIGO PROYECTO",
    pp."NOMBRE PROYECTO",
    pp."RESUMEN PROYECTO",
    pp."DIRECCIÓN PROYECTO",
    pp."FECHA REGISTRO",
    pp."CÓDIGO ACTIVIDAD",
    pp."ACTIVIDAD ECONÓMICA",
    pp."CED/RUC PROPONENTE",
    pp."NOMBRE PROPONENTE",
    pp."ÁREA RESPONSABLE PROYECTO",
    pp."TIPO SECTOR",
    pp."TIPO PERMISO AMBIENTAL",
    pp."TIPO ENTE",
    pp."PROVINCIA",
    pp."CANTON",
    pp."PARROQUIA",
    pp."PROCESO",
    pp."ESTADO PROCESO",
    pp."FECHA INICIO PROCESO",
    pp."FECHA FIN PROCESO",
    pp."TAREA",
    pp."ESTADO TAREA",
    pp."FECHA INICIO TAREA",
    pp."FECHA FIN TAREA",
    pp."USUARIO TAREA",
    pp."ESTADO PROYECTO",
    pp."INTERSECTA CON",
    pp."AREAS PROTEGIDAS",
    pp."SISTEMA",
    ''NA'' AS "NOMBRE ZONA",
    ''NA'' AS "FINALIZADO CON RESOLUCION",
    ''NA'' AS "NUMERO RESOLUCION",
    null AS "FECHA RESOLUCION",
    pp."ENTE ACREDITADO",
    pp."ESTADO TRÁMITE",
    0 AS "ID AREA",
    0 as "SUPERFICIE PROYECTO",
    pp."ESTRATÉGICO"
from public.vm_sector_subsector_bi pp order by 1, max desc
'::text) t3("CÓDIGO PROYECTO" character varying(255), "NOMBRE PROYECTO" text, "RESUMEN PROYECTO" text, "DIRECCIÓN PROYECTO" text, "FECHA REGISTRO" timestamp without time zone, "CÓDIGO ACTIVIDAD" text, "ACTIVIDAD ECONÓMICA" text, "CED/RUC PROPONENTE" text, "NOMBRE PROPONENTE" text, "ÁREA RESPONSABLE PROYECTO" text, "TIPO SECTOR" text, "TIPO PERMISO AMBIENTAL" text, "TIPO ENTE" text, "PROVINCIA" text, "CANTON" text, "PARROQUIA" text, "PROCESO" text, "ESTADO PROCESO" text, "FECHA INICIO PROCESO" timestamp without time zone, "FECHA FIN PROCESO" timestamp without time zone, "TAREA" text, "ESTADO TAREA" text, "FECHA INICIO TAREA" timestamp without time zone, "FECHA FIN TAREA" timestamp without time zone, "USUARIO TAREA" text, "ESTADO PROYECTO" text, "INTERSECTA CON" text, "AREAS PROTEGIDAS" text, "SISTEMA" text, "NOMBRE ZONA" character varying(500), "FINALIZADO CON RESOLUCION" character varying(500), "NUMERO RESOLUCION" character varying(500), "FECHA RESOLUCION" timestamp without time zone, "ENTE ACREDITADO" character varying(500), "ESTADO TRÁMITE" character varying(500), "ID AREA" integer, "SUPERFICIE PROYECTO" double precision, "ESTRATÉGICO" character varying(500))
        UNION ALL
         SELECT DISTINCT t4."CÓDIGO PROYECTO",
            t4."NOMBRE PROYECTO",
            t4."RESUMEN PROYECTO",
            t4."DIRECCIÓN PROYECTO",
            t4."FECHA REGISTRO",
            t4."CÓDIGO ACTIVIDAD",
            t4."ACTIVIDAD ECONÓMICA",
            t4."CED/RUC PROPONENTE",
            t4."NOMBRE PROPONENTE",
            t4."ÁREA RESPONSABLE PROYECTO",
            t4."TIPO SECTOR",
            t4."TIPO PERMISO AMBIENTAL",
            t4."TIPO ENTE",
            t4."PROVINCIA",
            t4."CANTON",
            t4."PARROQUIA",
            t4."PROCESO",
            t4."ESTADO PROCESO",
            t4."FECHA INICIO PROCESO",
            t4."FECHA FIN PROCESO",
            t4."TAREA",
            t4."ESTADO TAREA",
            t4."FECHA INICIO TAREA",
            t4."FECHA FIN TAREA",
            t4."USUARIO TAREA",
            t4."ESTADO PROYECTO",
            t4."INTERSECTA CON",
            t4."AREAS PROTEGIDAS",
            t4."SISTEMA",
            t4."NOMBRE ZONA",
            t4."FINALIZADO CON RESOLUCION",
            t4."NUMERO RESOLUCION",
            t4."FECHA RESOLUCION",
            t4."ENTE ACREDITADO",
            t4."ESTADO TRÁMITE",
            t4."ID AREA",
            t4."SUPERFICIE PROYECTO",
            t4."ESTRATÉGICO"
           FROM dblink('dbname= jbpmdb port=5432 host=172.16.0.226 user=postgres password=postgres'::text, '
select pp."CÓDIGO PROYECTO",
    pp."NOMBRE PROYECTO",
    pp."RESUMEN PROYECTO",
    pp."DIRECCIÓN PROYECTO",
    pp."FECHA REGISTRO",
    pp."CÓDIGO ACTIVIDAD",
    pp."ACTIVIDAD ECONÓMICA",
    pp."CED/RUC PROPONENTE",
    pp."NOMBRE PROPONENTE",
    pp."ÁREA RESPONSABLE PROYECTO",
    pp."TIPO SECTOR",
    pp."TIPO PERMISO AMBIENTAL",
    pp."TIPO ENTE",
    pp."PROVINCIA",
    pp."CANTON",
    pp."PARROQUIA",
    pp."PROCESO",
    pp."ESTADO PROCESO",
    pp."FECHA INICIO PROCESO",
    pp."FECHA FIN PROCESO",
    pp."TAREA",
    pp."ESTADO TAREA",
    pp."FECHA INICIO TAREA",
    pp."FECHA FIN TAREA",
    pp."USUARIO TAREA",
    pp."ESTADO PROYECTO",
    pp."INTERSECTA CON",
    pp."AREAS PROTEGIDAS",
    pp."SISTEMA",
    ''NA'' AS "NOMBRE ZONA",
    ''NA'' AS "FINALIZADO CON RESOLUCION",
    ''NA'' AS "NUMERO RESOLUCION",
    null AS "FECHA RESOLUCION",
    pp."ENTE ACREDITADO",
    pp."ESTADO TRÁMITE",
    0 AS "ID AREA",
    0 "SUPERFICIE PROYECTO",
    pp."ESTRATÉGICO"
from public.vm_cuatro_categorias_bi pp order by 1, max desc
 '::text) t4("CÓDIGO PROYECTO" character varying(255), "NOMBRE PROYECTO" text, "RESUMEN PROYECTO" text, "DIRECCIÓN PROYECTO" text, "FECHA REGISTRO" timestamp without time zone, "CÓDIGO ACTIVIDAD" text, "ACTIVIDAD ECONÓMICA" text, "CED/RUC PROPONENTE" text, "NOMBRE PROPONENTE" text, "ÁREA RESPONSABLE PROYECTO" text, "TIPO SECTOR" text, "TIPO PERMISO AMBIENTAL" text, "TIPO ENTE" text, "PROVINCIA" text, "CANTON" text, "PARROQUIA" text, "PROCESO" text, "ESTADO PROCESO" text, "FECHA INICIO PROCESO" timestamp without time zone, "FECHA FIN PROCESO" timestamp without time zone, "TAREA" text, "ESTADO TAREA" text, "FECHA INICIO TAREA" timestamp without time zone, "FECHA FIN TAREA" timestamp without time zone, "USUARIO TAREA" text, "ESTADO PROYECTO" text, "INTERSECTA CON" text, "AREAS PROTEGIDAS" text, "SISTEMA" text, "NOMBRE ZONA" character varying(500), "FINALIZADO CON RESOLUCION" character varying(500), "NUMERO RESOLUCION" character varying(500), "FECHA RESOLUCION" timestamp without time zone, "ENTE ACREDITADO" character varying(500), "ESTADO TRÁMITE" character varying(500), "ID AREA" integer, "SUPERFICIE PROYECTO" double precision, "ESTRATÉGICO" character varying(500))
        UNION ALL
         SELECT DISTINCT t5."CÓDIGO PROYECTO",
            t5."NOMBRE PROYECTO",
            t5."RESUMEN PROYECTO",
            t5."DIRECCIÓN PROYECTO",
            t5."FECHA REGISTRO",
            t5."CÓDIGO ACTIVIDAD",
            t5."ACTIVIDAD ECONÓMICA",
            t5."CED/RUC PROPONENTE",
            t5."NOMBRE PROPONENTE",
            t5."ÁREA RESPONSABLE PROYECTO",
            t5."TIPO SECTOR",
            t5."TIPO PERMISO AMBIENTAL",
            t5."TIPO ENTE",
            t5."PROVINCIA",
            t5."CANTON",
            t5."PARROQUIA",
            t5."PROCESO",
            t5."ESTADO PROCESO",
            t5."FECHA INICIO PROCESO",
            t5."FECHA FIN PROCESO",
            t5."TAREA",
            t5."ESTADO TAREA",
            t5."FECHA INICIO TAREA",
            t5."FECHA FIN TAREA",
            t5."USUARIO TAREA",
            t5."ESTADO PROYECTO",
            t5."INTERSECTA CON",
            t5."AREAS PROTEGIDAS",
            t5."SISTEMA",
            t5."NOMBRE ZONA",
            t5."FINALIZADO CON RESOLUCION",
            t5."NUMERO RESOLUCION",
            t5."FECHA RESOLUCION",
            t5."ENTE ACREDITADO",
            t5."ESTADO TRÁMITE",
            t5."ID AREA",
            t5."SUPERFICIE PROYECTO",
            t5."ESTRATÉGICO"
           FROM dblink('dbname= jbpmdb port=5432 host=172.16.0.226 user=postgres password=postgres'::text, '
select pp."CÓDIGO PROYECTO",
    pp."NOMBRE PROYECTO",
    pp."RESUMEN" AS "RESUMEN PROYECTO",
    pp."DIRECCIÓN PROYECTO",
    pp."FECHA REGISTRO",
    pp."CÓDIGO ACTIVIDAD",
    pp."ACTIVIDAD ECONÓMICA",
    pp."CED/RUC EMPRESA" AS "CED/RUC PROPONENTE",
    pp."NOMBRE EMPRESA" AS "NOMBRE PROPONENTE",
    pp."ÁREA RESPONSABLE PROYECTO",
    pp."TIPO SECTOR",
    ''Licencia Ambiental'' AS "TIPO PERMISO AMBIENTAL",
    pp."TIPO ENTE",
    pp."PROVINCIA",
    pp."CANTÓN" AS "CANTON",
    pp."PARROQUIA",
    pp."PROCESO",
    pp."ESTADO PROCESO",
    pp."FECHA INICIO PROCESO",
    pp."FECHA FIN PROCESO",
    pp."TAREA",
    pp."ESTADO TAREA",
    pp."FECHA INICIO TAREA",
    pp."FECHA FIN TAREA",
    pp."USUARIO TAREA",
    pp."ESTADO PROYECTO",
    pp."INTERSECTA CON",
    NULL AS "AREAS PROTEGIDAS",
    ''HIDROCARBUROS'' AS "SISTEMA",
    ''NA'' AS "NOMBRE ZONA", 
    ''NA'' AS "FINALIZADO CON RESOLUCION",
    ''NA'' AS "NUMERO RESOLUCION",
     NULL AS "FECHA RESOLUCION",
     pp."ENTE ACREDITADO",
     pp."ESTADO TRÁMITE",
     pp."ID AREA",
     0 as "SUPERFICIE PROYECTO",
     ''Planta Central'' as "ESTRATÉGICO"
from public.vwt_hidrocarbonos_bi pp
 '::text) t5("CÓDIGO PROYECTO" character varying(255), "NOMBRE PROYECTO" text, "RESUMEN PROYECTO" text, "DIRECCIÓN PROYECTO" text, "FECHA REGISTRO" timestamp without time zone, "CÓDIGO ACTIVIDAD" text, "ACTIVIDAD ECONÓMICA" text, "CED/RUC PROPONENTE" text, "NOMBRE PROPONENTE" text, "ÁREA RESPONSABLE PROYECTO" text, "TIPO SECTOR" text, "TIPO PERMISO AMBIENTAL" text, "TIPO ENTE" text, "PROVINCIA" text, "CANTON" text, "PARROQUIA" text, "PROCESO" text, "ESTADO PROCESO" text, "FECHA INICIO PROCESO" timestamp without time zone, "FECHA FIN PROCESO" timestamp without time zone, "TAREA" text, "ESTADO TAREA" text, "FECHA INICIO TAREA" timestamp without time zone, "FECHA FIN TAREA" timestamp without time zone, "USUARIO TAREA" text, "ESTADO PROYECTO" text, "INTERSECTA CON" text, "AREAS PROTEGIDAS" text, "SISTEMA" text, "NOMBRE ZONA" character varying(500), "FINALIZADO CON RESOLUCION" character varying(500), "NUMERO RESOLUCION" character varying(500), "FECHA RESOLUCION" timestamp without time zone, "ENTE ACREDITADO" character varying(500), "ESTADO TRÁMITE" character varying(500), "ID AREA" integer, "SUPERFICIE PROYECTO" double precision, "ESTRATÉGICO" text)) y
     LEFT JOIN r_perorga z ON z."CEDULA/RUC"::text = y."USUARIO TAREA"
     LEFT JOIN r_perorga w ON y."CED/RUC PROPONENTE" = w."CEDULA/RUC"::text
WITH DATA;

-- View indexes:
CREATE INDEX "vm_unificado_sistemas_bi_código_proyecto_idx" ON bi_dashboard.vm_unificado_sistemas_bi USING btree ("CÓDIGO PROYECTO");